-- This Particular Worksheet is used to emphasize Normalization, Foreign Keys, and Schema Design in Orcl sql developer
-- 

CREATE TABLE patient(
         patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY 
                    PRIMARY KEY,
         first_name VARCHAR2(50), 
         last_name VARCHAR2(50), 
         gender VARCHAR2(10),
         phone VARCHAR(20), 
         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE doctor(
       doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY 
                 PRIMARY KEY, 
       full_name VARCHAR2(50), 
       specialization VARCHAR2(50), 
       is_available NUMBER(1)
);

CREATE TABLE appointment(
         appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 50 
                        PRIMARY KEY, 
         patient_id NUMBER, 
         doctor_id NUMBER, 
         appointment_date DATE,
         status VARCHAR2(20), 
         CONSTRAINT fk_patient FOREIGN KEY (patient_id) REFERENCES patient(patient_id), 
         CONSTRAINT fk_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(doctor_id)
);

CREATE TABLE billing(
        bill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
        appointment_id NUMBER, 
        amount NUMBER(10, 2), 
        status VARCHAR2(20), 
        CONSTRAINT fk_appointment FOREIGN KEY (appointment_id) REFERENCES appointment(appointment_id)
);

